"""Brand Experience & Activation Lions judging criteria.

Pondération balanced toward Execution + Impact (experiential is craft-driven
AND outcome-driven), per the Cannes Lions 2026 entry kit:
    25% Idea  /  15% Strategy  /  30% Execution  /  30% Impact
"""
from typing import Literal


BXA_CRITERIA: dict = {
    "category": "Brand Experience & Activation",
    "definition": (
        "The Brand Experience & Activation Lions celebrate work that brings brands "
        "to life through experiences, activations, sponsorships, retail, partnerships, "
        "and live events. The work should immerse audiences and drive participation, "
        "not just deliver a message."
    ),
    "axes": [
        {"key": "idea", "name": "Experience Idea", "weight": 0.25,
         "description": "Originality of the experience concept. The unifying creative thought that organises the activation.",
         "signals": [
             "Uniqueness of the experience vs. category conventions",
             "Participation-led — invites the audience IN, not just past",
             "Cultural-moment exploitation",
             "Mnemonic power of the experience",
             "Translatability across markets",
         ]},
        {"key": "strategy", "name": "Strategy", "weight": 0.15,
         "description": "WHY this experience for this brand. Audience targeting, partnership logic, why-here-why-now reasoning.",
         "signals": [
             "WHO IS THE BRAND? Mission and territory",
             "Audience identification — narrow and specific",
             "Brand mission ↔ experience coherence",
             "Partnership / sponsorship logic when relevant",
             "Real cultural insight (not assumption)",
         ]},
        {"key": "execution", "name": "Execution", "weight": 0.30,
         "description": "HOW the experience was built and delivered. Production quality, interaction design, scale of execution.",
         "signals": [
             "Production craft (build quality, materials, fabrication)",
             "Interaction design — is participation easy and satisfying?",
             "Scale of execution (single-site vs. multi-market)",
             "Multi-phase orchestration (launch + amplification + sustain)",
             "Earned-media loop generated by the activation",
         ]},
        {"key": "impact", "name": "Impact & Results", "weight": 0.30,
         "description": "Audience participation + brand outcomes + cultural conversation. BXA needs documented PEOPLE who attended/participated.",
         "signals": [
             "Participation numbers (actual people who showed up / engaged)",
             "Brand metric shifts (awareness, consideration, sentiment)",
             "Business results (sales, traffic, sign-ups)",
             "Cultural conversation beyond the event window",
             "Behaviour or attitude change",
             "Earned-media multiplier",
         ]},
    ],
    "sub_categories_hint": {
        "A": "Sectors (CG, Healthcare, Auto, Travel, Media, B2B, NFP/Gov)",
        "B": "Brand Activation & Experiential",
        "C": "Use of Live Brand Experience",
        "D": "Sponsorship & Partnership",
        "E": "Excellence in Brand Experience (Use of Digital, Single-Market, Use of Tech)",
        "F": "Culture & Context (Local, Challenger, Single-Market, Behaviour, Humour, Budget, Purpose, Disruption)",
    },
}

Tier = Literal["Grand Prix", "Gold", "Silver", "Bronze", "Shortlist", "Loser"]
_BANDS = {"Grand Prix": (90, 100), "Gold": (80, 100), "Silver": (65, 80), "Bronze": (50, 65)}


def expected_score_range(tier: Tier) -> tuple[int, int] | None:
    return _BANDS.get(tier)


def tier_consistency(tier: Tier, weighted_score: float) -> Literal["expected", "below", "above", "n/a"]:
    band = _BANDS.get(tier)
    if band is None:
        return "n/a"
    low, high = band
    if weighted_score < low:
        return "below"
    if weighted_score > high:
        return "above"
    return "expected"
